{
 "title": "Django Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "traces",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "d7b4c6708f68ecb38d0c0e2a8b5c3214"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_server_duration_milliseconds_count{app_name=\"$app_name\"}) by(status)"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"200\"})",
     "legendFormat": " Success:"
    },
    {
     "expr": "sum by() (http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"500\"})",
     "legendFormat": "Internal Server Error: "
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"2.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"5.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"0\"}",
     "legendFormat": "cpu_number=\"0\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"1\"}",
     "legendFormat": "cpu_number=\"1\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"2\"}",
     "legendFormat": "cpu_number=\"2\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"3\"}",
     "legendFormat": "cpu_number=\"3\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"4\"}",
     "legendFormat": "cpu_number=\"4\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"5\"}",
     "legendFormat": "cpu_number=\"5\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"6\"}",
     "legendFormat": "cpu_number=\"6\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"7\"}",
     "legendFormat": "cpu_number=\"7\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"8\"}",
     "legendFormat": "cpu_number=\"8\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"9\"}",
     "legendFormat": "cpu_number=\"9\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"10\"}",
     "legendFormat": "cpu_number=\"10\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"11\"}",
     "legendFormat": "cpu_number=\"11\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"12\"}",
     "legendFormat": "cpu_number=\"12\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"13\"}",
     "legendFormat": "cpu_number=\"13\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"14\"}",
     "legendFormat": "cpu_number=\"14\""
    },
    {
     "expr": "sdk_djn_cpu_percent_ratio{cpu_number=\"15\"}",
     "legendFormat": "cpu_number=\"15\""
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sdk_djn_ram_percent_ratio{exported_job=\"otel-sdk-django-01\"}",
     "legendFormat": "ram_percent_ratio"
    }
   ]
  }
 ]
}