{
 "title": "Flask Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tracing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Service & Operation",
   "type": "traces",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "6a420ace52c67b4bcc0f1aa4ee97bc29"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_server_duration_milliseconds_count{app_name=\"$app_name\"}) by(status)"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"200\"})",
     "legendFormat": " Success:"
    },
    {
     "expr": "sum by() (http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"500\"})",
     "legendFormat": "Internal Server Error: "
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"2.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"5.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds_sum{app_name=\"flask-monitoring\"} / flask_request_duration_seconds_count{app_name=\"flask-monitoring\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"0\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"0\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"1\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"1\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"2\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"2\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"3\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"3\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"4\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"4\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"5\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"5\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"6\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"6\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"7\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"7\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"8\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"8\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"9\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"9\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"10\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"10\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"11\", exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "cpu_number=\"11\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"12\"}",
     "legendFormat": "cpu_number=\"12\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"13\"}",
     "legendFormat": "cpu_number=\"13\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"14\"}",
     "legendFormat": "cpu_number=\"14\""
    },
    {
     "expr": "sdk_fls_cpu_percent_ratio{cpu_number=\"15\"}",
     "legendFormat": "cpu_number=\"15\""
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sdk_fls_ram_percent_ratio{exported_job=\"otel-sdk-flask-01\"}",
     "legendFormat": "ram_percent_ratio"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$Application\", outcome=\"SUCCESS\", uri!=\"/health/server\"}[1m]) / rate(http_server_requests_seconds_count{instance=\"$Application\", outcome=\"SUCCESS\", uri!=\"/health/server\"}[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.5'}"
    },
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.9'}"
    },
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.99'}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds_sum{app_name=\"$app_name\"} / flask_request_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}