{
 "title": "Flask Monitoring",
 "description": "Flask Monitoring with StatsD",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": {
     "query": "label_values(flask_info{}, app_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_server_duration_milliseconds_count{app_name=\"$app_name\"}) by(status)"
    }
   ]
  },
  {
   "title": "Requests Per Status Code",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"200\"})",
     "legendFormat": " Success:"
    },
    {
     "expr": "sum by() (http_server_duration_milliseconds_count{http_method=\"GET\", http_status_code=\"500\"})",
     "legendFormat": "Internal Server Error: "
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"2.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{app_name=\"$app_name\", http_status_code=~\"5.*\"}) by(endpoint, method) / sum(http_server_duration_milliseconds_count{app_name=\"$app_name\"})",
     "legendFormat": "{{method}} {{endpoint}} "
    }
   ]
  },
  {
   "title": "CPU 사용량",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds_sum{app_name=\"flask-monitoring\"} / flask_request_duration_seconds_count{app_name=\"flask-monitoring\"}",
     "legendFormat": "{{method}} {{endpoint}}"
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"0\"}",
     "legendFormat": "cpu_number=\"0\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"1\"}",
     "legendFormat": "cpu_number=\"1\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"2\"}",
     "legendFormat": "cpu_number=\"2\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"3\"}",
     "legendFormat": "cpu_number=\"3\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"4\"}",
     "legendFormat": "cpu_number=\"4\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"5\"}",
     "legendFormat": "cpu_number=\"5\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"6\"}",
     "legendFormat": "cpu_number=\"6\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"7\"}",
     "legendFormat": "cpu_number=\"7\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"8\"}",
     "legendFormat": "cpu_number=\"8\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"9\"}",
     "legendFormat": "cpu_number=\"9\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"10\"}",
     "legendFormat": "cpu_number=\"10\""
    },
    {
     "expr": "cpu_percent_ratio{cpu_number=\"11\"}",
     "legendFormat": "cpu_number=\"11\""
    }
   ]
  },
  {
   "title": "메모리 사용량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "ram_percent_ratio", "legendFormat": "ram_percent_ratio" }
   ]
  },
  {
   "title": "Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{instance=\"$Application\", outcome=\"SUCCESS\", uri!=\"/health/server\"}[1m]) / rate(http_server_requests_seconds_count{instance=\"$Application\", outcome=\"SUCCESS\", uri!=\"/health/server\"}[1m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Request Duration Distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.5'}"
    },
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.9'}"
    },
    {
     "expr": "flask_request_duration_seconds{app_name=\"$app_name\", quantile='0.99'}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "flask_request_duration_seconds_sum{app_name=\"$app_name\"} / flask_request_duration_seconds_count{app_name=\"$app_name\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}