{
 "title": "SpringBoot(MSA) Monitoring",
 "description": "Dashboard for Spring Boot Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
   },
   {
    "name": "hikaricp",
    "label": "HikariCP-Pool",
    "query": "label_values(hikaricp_connections{application=\"$application\"}, pool)"
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Tracing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success",
   "type": "traces",
   "gridPos": { "h": 19, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "c6ad6bb84ba0681c3768d1bcbe1ba090"
    }
   ]
  },
  {
   "title": "LDAP Failure",
   "type": "traces",
   "gridPos": { "h": 19, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "5f97ffe27e1bfd51eb8e41afe5d0135a"
    }
   ]
  },
  {
   "title": "Duration Time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "703524c30cd0a6dbc934677e6a690e32",
     "service": "board-system"
    }
   ]
  },
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{application=\"$application\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{application=\"$application\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_load_average_1m{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 9, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon_threads{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak{instance=~\"$instance\", application=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Response Time",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/board\", status=\"200\"}",
     "legendFormat": "url=\"/board\", status=\"200\""
    },
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/board\", status=\"500\"}",
     "legendFormat": "url=\"/board\", status=\"500\""
    },
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/user\", status=\"200\"}",
     "legendFormat": "url=\"/user\", status=\"200\""
    },
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/user\", status=\"500\"}",
     "legendFormat": "url=\"/user\", status=\"500\""
    },
    {
     "expr": "http_server_requests_seconds_sum{uri=\"/log\"}",
     "legendFormat": "url=\"/log\", status=\"200\""
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "logback_events_total{instance=~\"$instance\", application=\"$application\", level=\"error\"}",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}