receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:9999
      http:
        endpoint: 127.0.0.1:4318
  postgresql:
    endpoint: 127.0.0.1:5432
    transport: tcp
    username: otel-user
    password: otel-user
    databases:
      - otel
    tls:
      insecure: true
    collection_interval: 10s

exporters:
  logging :
    verbosity: detailed
  file: # the File Exporter, to ingest logs to local file
    path: example.log
    rotation:
  prometheus:
    endpoint: 127.0.0.1:9464 # 프로메테우스에서 수집에 사용하는 IP
  
  otlp/jaeger:
    endpoint: 127.0.0.1:4317
    tls :
      insecure : true


processors:
  batch:

service:
  pipelines:
    logs/dev:
      receivers: [otlp]
      exporters: [file]
      processors: [batch]
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger,file]
      processors: [batch]
    metrics:
      receivers: [postgresql,otlp]
      exporters: [prometheus]
      processors: [batch]