{
 "title": "memory",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "system_utilization_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system_used_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "system_memory_usage_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_usesd_memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "jvm_memory_usedMemory", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_heap_used_memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    { "expr": "jvm_memory_heapUsage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_free_mmemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "jvm_memory_freeMemory", "legendFormat": "__auto" }
   ]
  }
 ]
}