# Generated by Django 5.0.6 on 2024-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='log_api',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(max_length=15)),
                ('user_id', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('call_url', models.CharField(max_length=100)),
                ('call_url_parameter', models.CharField(max_length=300)),
            ],
        ),
    ]
