# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x08oteldemo\"B\n\x1aListRecommendationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x13\n\x0bproduct_ids\x18\x02 \x03(\t\"2\n\x1bListRecommendationsResponse\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t2}\n\x15RecommendationService\x12\x64\n\x13ListRecommendations\x12$.oteldemo.ListRecommendationsRequest\x1a%.oteldemo.ListRecommendationsResponse\"\x00\x42\x13Z\x11genproto/oteldemob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\021genproto/oteldemo'
  _globals['_LISTRECOMMENDATIONSREQUEST']._serialized_start=24
  _globals['_LISTRECOMMENDATIONSREQUEST']._serialized_end=90
  _globals['_LISTRECOMMENDATIONSRESPONSE']._serialized_start=92
  _globals['_LISTRECOMMENDATIONSRESPONSE']._serialized_end=142
  _globals['_RECOMMENDATIONSERVICE']._serialized_start=144
  _globals['_RECOMMENDATIONSERVICE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
