spring:
  application:
    name: otel-sdk-springboot-01
  datasource :
    url:  jdbc:h2:~/otel
    #url:  jdbc:h2:tcp:localhost/~/otel
    username : sa
    password :
    driver-class-name : org.h2.Driver
  jpa :
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.sql : debug
  org.hibernate.type : trace

server :
  port : 8080


otel:
  service:
    name: otel-sdk-springboot-01-app
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  exporter:
    otlp:
      endpoint: 127.0.0.1:4317
  metric:
    export:
      interval: 1000 #옵션이 적용 안됨

