spring:
  application:
    name: otel-sdk-springboot-01
  datasource :
    url:  jdbc:h2:~/otel
    #url:  jdbc:h2:tcp:localhost/~/otel
    username : sa
    password :
    driver-class-name : org.h2.Driver
  jpa :
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console: # H2 DB? ??? ??? ? ?? ??
      enabled: true           # H2 Console ?? ??
      path: /h2-console       # H2 Console ?? ??

server :
  port : 8080

logging.level:
  org.hibernate.sql : debug
  org.hibernate.type : trace