spring:
  application:
    name: otel-sdk-springboot-01
  datasource :
    url:  jdbc:h2:~/otel
    #url:  jdbc:h2:tcp:localhost/~/otel
    username : sa
    password :
    driver-class-name : org.h2.Driver
  jpa :
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: info
        type:
          descriptor: info
        engine: info
    org.hibernate: info
    org.springframework: info
    #io.opentelemetry.exporter.logging.* : INFO
    root: INFO
    com.kt.otelsdkspringboot01 : INFO

server :
  port : 19090

management:
  endpoints:
    web:
      exposure:
        include: "*"
