spring:
  application:
    name: otel-agent-springboot-01
  datasource :
    url:  jdbc:h2:~/otel-agent
    username : sa
    password :
    driver-class-name : org.h2.Driver
  jpa :
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 5050